### PR TITLE
Update version to 2022.09.15-5

### PR DESCRIPTION
**Pull request by Ferenc-**
Signed-off-by: Ferenc Géczi <ferenc.gm@gmail.com>

### CODE REVIEW

**Comment by biodranik** [comment]
ICU cloning fails because of LFS. We don't need ICU's files in LFS, so it can be ignored, for example, using these approaches: https://stackoverflow.com/questions/42019529/how-to-clone-pull-a-git-repository-ignoring-lfs

**Comment by Ferenc-** [comment]
> ICU cloning fails because of LFS. We don't need ICU's files in LFS, so it can be ignored, for example, using these approaches: https://stackoverflow.com/questions/42019529/how-to-clone-pull-a-git-repository-ignoring-lfs

Thanks for the pointer. On my systems this error doesn't happen. And the LFS object is definitely valid and available for me,
testable with this snippet:
````
temporary_download_url=$(curl -X POST \
-H "Accept: application/vnd.git-lfs+json" \
-H "Content-type: application/json" \
-d '{"operation": "download", "transfer": ["basic"], "objects": [{"oid": "44951f88294c06e433a3b61238d9bb5f59ba01f091fcfb8fe4966f98f0748ef7", "size": 13627084}]}' \
https://github.com/unicode-org/icu.git/info/lfs/objects/batch \
| jq -r ".objects[0].actions.download.href")

echo "Download URL is: '${temporary_download_url}'"

curl --output icudata.jar ${temporary_download_url}
````

But from the `remote missing object 44951f88294c06e433a3b61238d9bb5f59ba01f091fcfb8fe4966f98f0748ef7`
I assume somehow it is not available for the flathub buildbot environment. My hope is that this is temporary or fixable in that environment, as in the [flatpak manifest](https://github.com/flatpak/flatpak-builder/blob/main/data/flatpak-manifest.schema.json#L749) I don't seem to find a way to pass in an environment variable or flag etc, to customize how the git submodule init is performed for an individual git submodule.
It could be turned off completely though, and then perhaps we could do a one by one manual initialization where needed?
But that is rather complicated.
Perhaps we should contact flathub people.

**Comment by Ferenc-** [comment]
It appear that other projects have hit the same issue before:
https://github.com/flathub/backend/issues/50
And if I understand correctly, then their way out of it, was to switch from a git [submodule to an archive](https://github.com/flathub/flathub/pull/2247/commits/4e9d992526233fbd64c8571faa90f24438f64be9).

**Comment by biodranik** [comment]
Sorry, I did not understand: did disable LFS smudge (for example, by setting the env var `GIT_LFS_SKIP_SMUDGE=1`) help?

**Comment by Ferenc-** [comment]
> Sorry, I did not understand: did disable LFS smudge (for example, by setting the env var `GIT_LFS_SKIP_SMUDGE=1`) help?

During a flatpak build, the fetching of the sources (in this case) from git, can't be customized on the level of git config nor, with environment variables, therefore the `GIT_LFS_SKIP_SMUDGE=1` can't be passed in time, for the submodule initialization to consider it. Wherever it is possible to pass in it is too late.
For example one might thing that simply disabling the submodule initialization in the source fetching time, and fetching the submodules in the build step would fly, it doesn't appear to work because by default there is no network access at that stage.

So for now all I can think of is going themor mainstream way, of easing the exclusive dependency on the vendored `3party` libraries, and at least allow external / system libraries to be used. And then we can have these dependencies in flatpak modules.
This would have multiple addedd benefits, for example distro packagers would have a chance to package organicmaps,
and also the flatpak re-build etc would be much faster, if we don't need to fetch the whole boost library with every rebuild etc.
So if you are OK with that, then I would start sending PRs upstream to allow CMake to consider system libraries.

**Comment by biodranik** [comment]
We already had a long discussion on that topic in https://github.com/organicmaps/organicmaps/pull/2863

To clarify and summarize:
1. I completely support easier builds by maintainers.
2. OM should work on as many systems as possible.
3. Contributors should have no issues in building and testing OM on their systems, even if they don't have the latest 3p lib installed.

Regarding the icu, maybe we can find some other option? It should already use the system library btw (but I believe that we had a .dat file with the ICU version hardcoded somewhere, so how it will work?).
Maybe you can temporarily try to checkout submodules one by one?

**Comment by Ferenc-** [comment]
> We already had a long discussion on that topic in [organicmaps/organicmaps#2863](https://github.com/organicmaps/organicmaps/pull/2863)
> 
> To clarify and summarize:
> 
> 1. I completely support easier builds by maintainers.
> 2. OM should work on as many systems as possible.
> 3. Contributors should have no issues in building and testing OM on their systems, even if they don't have the latest 3p lib installed.
> 
> Regarding the icu, maybe we can find some other option? It should already use the system library btw (but I believe that we had a .dat file with the ICU version hardcoded somewhere, so how it will work?). Maybe you can temporarily try to checkout submodules one by one?

In the [latest commit](https://github.com/flathub/app.organicmaps.desktop/pull/16/commits/6e4d6354220d231706c0711ee6f5f89c74f0615b), I have changed to flatpak managed dependencies,  
in the commit message I wrote down my views with pros and cons.
I hope that this would be an acceptable compromise.

**Review by biodranik — CHANGES_REQUESTED** [review]
That solution is not robust and will lead to build/runtime errors when 3party modules go out of sync.

1. Did you file an issue on Flatpak about that error? You can also ask them to add an option to disable LFS completely as an alternative.
2. Why can't you run a custom "git submodule --init --recursive" command using a "type: shell" with a proper env var set to disable smuggle?

**Comment by Ferenc-** [comment]
> 1. Did you file an issue on Flatpak about that error?  

I was under the impression, that the error is **not** flat**pak** specific, as local builds don't have such problems on my side. I believe it is flat**hub** specific. I have reported that to [flathub here](https://github.com/flathub/flathub/issues/3514).

> 2. Why can't you run a custom "git submodule --init --recursive" command using a "type: shell" with a proper env var set to disable smuggle?   

I have tried previously to communicate my point [here](https://github.com/flathub/app.organicmaps.desktop/pull/16#issuecomment-1261227915) and [there (the last point under Motivation)](https://github.com/Ferenc-/app.organicmaps.desktop/commit/6e4d6354220d231706c0711ee6f5f89c74f0615b), which is part of the [documentation too](https://github.com/flatpak/flatpak-builder/blob/main/doc/flatpak-manifest.xml#L1072):  

 _"the build sandbox is very limited, for example there is **no network access**"_.  
 
So having this:
````yaml
  - type: shell
    commands:
      - 'git submodule update --init --recursive'
````
Results in a bunch of error messages, at least on my side:
````
fatal: unable to access 'https://github.com/boostorg/boost.git/': Could not resolve host: github.com
````
I think this corresponds to the **no network access** in the build sandbox statement.  
But please do correct me if I am mistaken and it works for you. I would honestly liked if this was that simple.

**Comment by biodranik** [comment]
My bad, I was wrong. There is also another option:
1. Remove the ICU submodule.
2. Take the latest ICU release and add only the necessary folders of the ICU submodule into the main repo (without LFS, we don't need it).
3. Then try to find a system package and fall back to the embedded code, as we discussed.

It will make it a bit harder to update ICU but may be worth it. Honestly, they should not use LFS at all...

**Comment by fgaz** [comment]
The smudge thing also happened when I created the package, see https://github.com/flathub/flathub/pull/2968#issuecomment-1084902063 and later comments. I think @barthalion fixed it on the flathub infra side. Not sure why it resurfaced.

**Comment by biodranik** [comment]
Maybe the build machine was updated or a new one was used? @barthalion can you help please?

**Comment by Ferenc-** [comment]
> Maybe the build machine was updated or a new one was used? @barthalion can you help please?

Yes, something very similar. He says [he will look into it](https://discourse.flathub.org/t/lfs-smudge-error-on-flathub/3143).

**Comment by Ferenc-** [comment]
@biodranik In the meantime I found a way to re-enable network access at build time, but I think it is not the best from security perspective. And from the perspective of the developer experience experience, this current proposal is better,
rebuilds are much faster, and one can oversee the dependencies much better. And as I expressed in the [last commit message](https://github.com/flathub/app.organicmaps.desktop/pull/16/commits/6e4d6354220d231706c0711ee6f5f89c74f0615b),
I think this way we can leverage automation to automatically update dependencies.
The way I see people typically use the [Anytia service](https://release-monitoring.org/).

I understand your concerns about fragility, and I think for example having a CI job for flatpak builds in the upstream repo,
could eliminate any questions about which version to use for flatpak builds, and perhaps we could make that proposed upstream flatpak manifest as a submodule of this, or try to set up automatic synchronization.

**Comment by biodranik** [comment]
The core issue is a bug on some build machine with LFS. Everything else is an unnecessary workaround, distracting everyone and taking our time. The problem is solved if you can fix the bug at the core. Let's focus on that.

**Comment by barthalion** [comment]
bot, build

**Comment by barthalion** [comment]
This should be fixed now.

**Pull request closed without merging**
