### PR TITLE
remove branch property to fix commit vs branch mismatch for beta 

### PR DESCRIPTION
**Pull request by bam80**
Fixes https://github.com/flathub/flathub/issues/4268

### CODE REVIEW

**Comment by bam80** [comment]
Seems like unrelated fail?

**Comment by Ferenc-** [comment]
I have raised an issue here: https://github.com/flathub/flathub/issues/4272

**Comment by bam80** [comment]
Still we can merge this?

**Comment by Ferenc-** [comment]
> Still we can merge this?

The branch protection rules don't allow that, and I believe only flathub team can override or change that.

**Comment by bam80** [comment]
What do you mean, sorry? As we can see above it passed the manifest validation at least?

**Comment by bam80** [comment]
Hi Ferenc, seems it's all moving with a very slow pace, if you don't have time even for reply, maybe you will give me an access so I could try things too?
I still don't understand why the branch protection rules can prevent from merging the MR, though. Last time you was able to do it?

I also asked on forum:
https://discourse.flathub.org/t/enforcing-branch-protection-on-existing-repositories/1935

**Comment by hfiguiere** [comment]
> What do you mean, sorry? As we can see above it passed the manifest validation at least?

the build failed so it can't be merged. Period.

I have no idea what the git-lfs issue is about.

**Comment by bam80** [comment]
> I have no idea what the git-lfs issue is about.

This issue apparently comes from Flathub infrastructure. Do you know if somebody knows better? Otherwise we are just stuck here.

**Comment by barthalion** [comment]
bot, build

**Comment by bam80** [comment]
@Ferenc- do you think we actually need this PR or alternatively just bump the beta to actual master when needed?
#41 

Do not forget to squash the commits if you decide to merge this please.

**Review by biodranik — APPROVED** [review]

**Pull request merged**
