### PR TITLE
test if it builds

### PR DESCRIPTION
**Pull request by bam80**

### CODE REVIEW

**Comment by barthalion** [comment]
bot, build

**Comment by bam80** [comment]
I see the error is now different, @barthalion would you comment on your changes and thoughts how to solve it?

**Comment by barthalion** [comment]
I'm still working on it. I'm not excluding a bug in flatpak-builder, but given it works for stable builds and doesn't here, I suspect there's something wrong with your repo or one of git submodules after all.

**Comment by bam80** [comment]
Note it doesn't work for the stable builds either, I created this PR for `master` specially to test it.

**Comment by barthalion** [comment]
So did I, and the build actually builds instead of failing on fetching sources. See https://buildbot.flathub.org/#/builders/6/builds/49694 -- I cancelled it as there was no point to let it finish.

**Comment by bam80** [comment]
I do not understand the conclusions, your build is manual but here we see they fail with the other error:  
```
FB: Running: git rev-parse a738fdf9338412f83ab3f26f31ac11ed3f3ec4bd
FB: Running: git rev-parse --verify --quiet a738fdf9338412f83ab3f26f31ac11ed3f3ec4bd:.gitmodules
]2;flatpak-builder: Downloading organicmaps]2;flatpak-builder: Downloading organicmaps
(flatpak-builder:2): OSTree-CRITICAL **: 13:54:01.621: ostree_repo_open: assertion 'error == NULL || *error == NULL' failed
Error opening cache: opening repo: Creating repo: Child process exited with code 2
program finished with exit code 1

**Comment by barthalion** [comment]
I mean, it doesn't for the build I linked, that's my point. The only thing different between working and broken build is the used commit.

**Comment by bam80** [comment]
I changed the commit here to be closest possible to your successful build.
The major difference now is the runtime has also been changed in the manifest.

**Comment by barthalion** [comment]
Thanks. I will poke around locally later today.

**Comment by barthalion** [comment]
bot, build

**Comment by barthalion** [comment]
At this point, I really don't understand what is going on here.

**Comment by barthalion** [comment]
To make this even more confusing, the build generally works if I restart the flatpak-builder process locally, re-using the files downloaded during the first run. I will keep poking.

**Comment by bam80** [comment]
That's a progress! So what's the conclusion?
For now, the build should be manually restarted to succeed?

**Comment by bam80** [comment]
So it fails again, could you restart the build in the middle as you did before?

**Comment by barthalion** [comment]
bot, build

**Comment by bam80** [comment]
@barthalion thank you for your efforts, please keep me updated what you have gathered so far.

**Comment by barthalion** [comment]
This should be reliably fixed on our end now.

**Comment by bam80** [comment]
@barthalion can you link the fix here please?  
From what I can see https://github.com/flathub/app.organicmaps.desktop/pull/37 still doesn't build.

**Comment by barthalion** [comment]
You didn't trigger a new build, so obviously it's still in failed state.

**Comment by bam80** [comment]
> @barthalion can you link the fix here please?

@barthalion Can I see the fixes please?

**Comment by barthalion** [comment]
The fix on the infrastructure side. What exactly do you want to see?

**Comment by bam80** [comment]
@barthalion I understand, I would like to see all the changes which made it build properly now. Thanks.

**Comment by bam80** [comment]
> The fix is on the infrastructure side. What exactly do you want to see?

@barthalion Does the infrastructure code publicly accessible? There should be commits/PR then, isn't it?
Could you provide them please?

**Pull request closed without merging**
