### PR TITLE
Add debug info

### LINKED ISSUE #45: there are no debug symbols in .Debug extension
One should be able to install `.Debug` extension to get debug information for the app:
https://docs.flatpak.org/en/latest/debugging.html#creating-a-debug-extension

The current `Debug` extension contains only the sources and no debug information:
```
$ flatpak install --user flathub app.organicmaps.desktop.Debug

$ flatpak info --show-location  app.organicmaps.desktop.Debug 
/home/bam/.local/share/flatpak/runtime/app.organicmaps.desktop.Debug/x86_64/stable/66560619504fb3cb1089115d76ca966324a13d405df5ac480950e9d0267d12f3

$ ll /home/bam/.local/share/flatpak/runtime/app.organicmaps.desktop.Debug/ -R
/home/bam/.local/share/flatpak/runtime/app.organicmaps.desktop.Debug/:
total 12
drwxr-xr-x  3 bam bam 4096 июл  4 20:25 ./
drwxr-xr-x 32 bam bam 4096 июл  4 20:25 ../
drwxr-xr-x  3 bam bam 4096 июл  4 20:25 x86_64/

/home/bam/.local/share/flatpak/runtime/app.organicmaps.desktop.Debug/x86_64:
total 12
drwxr-xr-x 3 bam bam 4096 июл  4 20:25 ./
drwxr-xr-x 3 bam bam 4096 июл  4 20:25 ../
drwxr-xr-x 3 bam bam 4096 июл  4 20:25 stable/

/home/bam/.local/share/flatpak/runtime/app.organicmaps.desktop.Debug/x86_64/stable:
total 16
drwxr-xr-x 3 bam bam 4096 июл  4 20:25 ./
drwxr-xr-x 3 bam bam 4096 июл  4 20:25 ../
drwxr-xr-x 3 bam bam 4096 июл  4 20:25 66560619504fb3cb1089115d76ca966324a13d405df5ac480950e9d0267d12f3/
lrwxrwxrwx 1 bam bam   64 июл  4 20:25 active -> 66560619504fb3cb1089115d76ca966324a13d405df5ac480950e9d0267d12f3/

/home/bam/.local/share/flatpak/runtime/app.organicmaps.desktop.Debug/x86_64/stable/66560619504fb3cb1089115d76ca966324a13d405df5ac480950e9d0267d12f3:
total 20
drwxr-xr-x 3 bam bam 4096 июл  4 20:25 ./
drwxr-xr-x 3 bam bam 4096 июл  4 20:25 ../
-rw-r--r-- 1 bam bam  209 июл  4 20:25 deploy
drwxr-xr-x 3 bam bam 4096 июл  4 20:25 files/
-rw-r--r-- 2 bam bam  106 янв  1  1970 metadata

/home/bam/.local/share/flatpak/runtime/app.organicmaps.desktop.Debug/x86_64/stable/66560619504fb3cb1089115d76ca966324a13d405df5ac480950e9d0267d12f3/files:
total 12
drwxr-xr-x 3 bam bam 4096 июл  4 20:25 ./
drwxr-xr-x 3 bam bam 4096 июл  4 20:25 ../
-rw-r--r-- 1 bam bam    0 июл  4 20:25 .ref
drwxr-xr-x 3 bam bam 4096 янв  1  1970 source/

/home/bam/.local/share/flatpak/runtime/app.organicmaps.desktop.Debug/x86_64/stable/66560619504fb3cb1089115d76ca966324a13d405df5ac480950e9d0267d12f3/files/source:
total 12
drwxr-xr-x 3 bam bam 4096 янв  1  1970 ./
drwxr-xr-x 3 bam bam 4096 июл  4 20:25 ../
drwxr-xr-x 5 bam bam 4096 янв  1  1970 rsync/

/home/bam/.local/share/flatpak/runtime/app.organicmaps.desktop.Debug/x86_64/stable/66560619504fb3cb1089115d76ca966324a13d405df5ac480950e9d0267d12f3/files/source/rsync:
total 1124
drwxr-xr-x 5 bam bam  4096 янв  1  1970 ./
drwxr-xr-x 3 bam bam  4096 янв  1  1970 ../
-rw-r--r-- 2 bam bam  6202 янв  1  1970 access.c
-rw-r--r-- 2 bam bam 30515 янв  1  1970 acls.c
-rw-r--r-- 2 bam bam  9872 янв  1  1970 authenticate.c
-rw-r--r-- 2 bam bam  9307 янв  1  1970 backup.c
-rw-r--r-- 2 bam bam  8063 янв  1  1970 batch.c
-rw-r--r-- 2 bam bam  2937 янв  1  1970 byteorder.h
-rw-r--r-- 2 bam bam 15745 янв  1  1970 checksum.c
-rw-r--r-- 2 bam bam  5598 янв  1  1970 chmod.c
-rw-r--r-- 2 bam bam  7798 янв  1  1970 cleanup.c
-rw-r--r-- 2 bam bam 13747 янв  1  1970 clientname.c
-rw-r--r-- 2 bam bam 39031 янв  1  1970 clientserver.c
-rw-r--r-- 2 bam bam 23528 янв  1  1970 compat.c
-rw-r--r-- 2 bam bam  1367 янв  1  1970 connection.c
-rw-r--r-- 2 bam bam 11551 янв  1  1970 daemon-parm.h
-rw-r--r-- 2 bam bam  6498 янв  1  1970 delete.c
-rw-r--r-- 2 bam bam 41025 янв  1  1970 exclude.c
-rw-r--r-- 2 bam bam  8277 янв  1  1970 fileio.c
-rw-r--r-- 2 bam bam 91533 янв  1  1970 flist.c
-rw-r--r-- 2 bam bam 67890 янв  1  1970 generator.c
-rw-r--r-- 2 bam bam 16495 янв  1  1970 hashtable.c
-rw-r--r-- 2 bam bam  1090 янв  1  1970 help-rsyncd.h
-rw-r--r-- 2 bam bam 11250 янв  1  1970 help-rsync.h
-rw-r--r-- 2 bam bam 15874 янв  1  1970 hlink.c
-rw-r--r-- 2 bam bam  2223 янв  1  1970 ifuncs.h
-rw-r--r-- 2 bam bam  1486 янв  1  1970 inums.h
-rw-r--r-- 2 bam bam 65085 янв  1  1970 io.c
-rw-r--r-- 2 bam bam  1292 янв  1  1970 io.h
-rw-r--r-- 2 bam bam  1433 янв  1  1970 itypes.h
drwxr-xr-x 2 bam bam  4096 янв  1  1970 lib/
-rw-r--r-- 2 bam bam 15215 янв  1  1970 loadparm.c
-rw-r--r-- 2 bam bam 24515 янв  1  1970 log.c
-rw-r--r-- 2 bam bam 49501 янв  1  1970 main.c
-rw-r--r-- 2 bam bam 12628 янв  1  1970 match.c
-rw-r--r-- 2 bam bam 92776 янв  1  1970 options.c
-rw-r--r-- 2 bam bam 21805 янв  1  1970 params.c
-rw-r--r-- 2 bam bam  5202 янв  1  1970 pipe.c
drwxr-xr-x 2 bam bam  4096 янв  1  1970 popt/
-rw-r--r-- 2 bam bam  6425 янв  1  1970 progress.c
-rw-r--r-- 2 bam bam 21406 янв  1  1970 proto.h
-rw-r--r-- 2 bam bam 27551 янв  1  1970 receiver.c
-rw-r--r-- 2 bam bam 23815 янв  1  1970 rsync.c
-rw-r--r-- 2 bam bam 41134 янв  1  1970 rsync.h
-rw-r--r-- 2 bam bam 11208 янв  1  1970 sender.c
-rw-r--r-- 2 bam bam 21958 янв  1  1970 socket.c
-rw-r--r-- 2 bam bam 14134 янв  1  1970 syscall.c
-rw-r--r-- 2 bam bam 26790 янв  1  1970 token.c
-rw-r--r-- 2 bam bam 14071 янв  1  1970 uidlist.c
-rw-r--r-- 2 bam bam  6276 янв  1  1970 usage.c
-rw-r--r-- 2 bam bam  3565 янв  1  1970 util2.c
-rw-r--r-- 2 bam bam 41684 янв  1  1970 util.c
-rw-r--r-- 2 bam bam 32448 янв  1  1970 xattrs.c
drwxr-xr-x 2 bam bam  4096 янв  1  1970 zlib/

/home/bam/.local/share/flatpak/runtime/app.organicmaps.desktop.Debug/x86_64/stable/66560619504fb3cb1089115d76ca966324a13d405df5ac480950e9d0267d12f3/files/source/rsync/lib:
total 200
drwxr-xr-x 2 bam bam  4096 янв  1  1970 ./
drwxr-xr-x 5 bam bam  4096 янв  1  1970 ../
-rw-r--r-- 2 bam bam  6227 янв  1  1970 compat.c
-rw-r--r-- 2 bam bam  7532 янв  1  1970 md5.c
-rw-r--r-- 2 bam bam  6113 янв  1  1970 mdfour.c
-rw-r--r-- 2 bam bam   856 янв  1  1970 mdigest.h
-rw-r--r-- 2 bam bam  1832 янв  1  1970 permstring.c
-rw-r--r-- 2 bam bam    71 янв  1  1970 permstring.h
-rw-r--r-- 2 bam bam  9015 янв  1  1970 pool_alloc.c
-rw-r--r-- 2 bam bam   885 янв  1  1970 pool_alloc.h
-rw-r--r-- 2 bam bam 36092 янв  1  1970 snprintf.c
-rw-r--r-- 2 bam bam 67142 янв  1  1970 sysacls.c
-rw-r--r-- 2 bam bam  8008 янв  1  1970 sysacls.h
-rw-r--r-- 2 bam bam  7060 янв  1  1970 sysxattrs.c
-rw-r--r-- 2 bam bam   728 янв  1  1970 sysxattrs.h
-rw-r--r-- 2 bam bam  9611 янв  1  1970 wildmatch.c
-rw-r--r-- 2 bam bam   282 янв  1  1970 wildmatch.h

/home/bam/.local/share/flatpak/runtime/app.organicmaps.desktop.Debug/x86_64/stable/66560619504fb3cb1089115d76ca966324a13d405df5ac480950e9d0267d12f3/files/source/rsync/popt:
total 116
drwxr-xr-x 2 bam bam  4096 янв  1  1970 ./
drwxr-xr-x 5 bam bam  4096 янв  1  1970 ../
-rw-r--r-- 2 bam bam  1300 янв  1  1970 findme.c
-rw-r--r-- 2 bam bam   504 янв  1  1970 findme.h
-rw-r--r-- 2 bam bam 35451 янв  1  1970 popt.c
-rw-r--r-- 2 bam bam  4586 янв  1  1970 poptconfig.c
-rw-r--r-- 2 bam bam 16314 янв  1  1970 popt.h
-rw-r--r-- 2 bam bam 22601 янв  1  1970 popthelp.c
-rw-r--r-- 2 bam bam  2880 янв  1  1970 poptint.h
-rw-r--r-- 2 bam bam  5343 янв  1  1970 poptparse.c
-rw-r--r-- 2 bam bam  2697 янв  1  1970 system.h

/home/bam/.local/share/flatpak/runtime/app.organicmaps.desktop.Debug/x86_64/stable/66560619504fb3cb1089115d76ca966324a13d405df5ac480950e9d0267d12f3/files/source/rsync/zlib:
total 444
drwxr-xr-x 2 bam bam  4096 янв  1  1970 ./
drwxr-xr-x 5 bam bam  4096 янв  1  1970 ../
-rw-r--r-- 2 bam bam  4968 янв  1  1970 adler32.c
-rw-r--r-- 2 bam bam  2529 янв  1  1970 compress.c
-rw-r--r-- 2 bam bam 13150 янв  1  1970 crc32.c
-rw-r--r-- 2 bam bam 30562 янв  1  1970 crc32.h
-rw-r--r-- 2 bam bam 72069 янв  1  1970 deflate.c
-rw-r--r-- 2 bam bam 12774 янв  1  1970 deflate.h
-rw-r--r-- 2 bam bam 12911 янв  1  1970 inffast.c
-rw-r--r-- 2 bam bam   427 янв  1  1970 inffast.h
-rw-r--r-- 2 bam bam  6332 янв  1  1970 inffixed.h
-rw-r--r-- 2 bam bam 54096 янв  1  1970 inflate.c
-rw-r--r-- 2 bam bam  6443 янв  1  1970 inflate.h
-rw-r--r-- 2 bam bam 13005 янв  1  1970 inftrees.c
-rw-r--r-- 2 bam bam  2928 янв  1  1970 inftrees.h
-rw-r--r-- 2 bam bam 44255 янв  1  1970 trees.c
-rw-r--r-- 2 bam bam  8472 янв  1  1970 trees.h
-rw-r--r-- 2 bam bam 15508 янв  1  1970 zconf.h
-rw-r--r-- 2 bam bam 87907 янв  1  1970 zlib.h
-rw-r--r-- 2 bam bam  7728 янв  1  1970 zutil.c
-rw-r--r-- 2 bam bam  6703 янв  1  1970 zutil.h
$ 
```

I guess it might be something wrong from our side.

CC: @hfiguiere @barthalion

### PR DESCRIPTION
**Pull request by bam80**
Closes #45

### CODE REVIEW

**Comment by bam80** [comment]
This doesn't add size to the binary:
```
$ ls --size -1 /home/bam/.local/share/flatpak/app/app.organicmaps.desktop/x86_64/test/active/files/bin/OMaps \
> /home/bam/.local/share/flatpak/app/app.organicmaps.desktop/x86_64/stable/active/files/bin/OMaps 
17756 /home/bam/.local/share/flatpak/app/app.organicmaps.desktop/x86_64/stable/active/files/bin/OMaps
17756 /home/bam/.local/share/flatpak/app/app.organicmaps.desktop/x86_64/test/active/files/bin/OMaps
```

**Comment by Ferenc-** [comment]
@bam80 I have flatpak `1.15.4`,
and I have installed the test build with `flatpak --user install --include-debug https://dl.flathub.org/build-repo/33767/app.organicmaps.desktop.flatpakref` and I still don't see any debug symbols anywhere:
````
Reading symbols from /app/bin/OMaps...
(No debugging symbols found in /app/bin/OMaps
````
How did you test this build?

**Comment by bam80** [comment]
It's expected debug symbols will be available in `.Debug` extension once the build will be published on master.

**Comment by Ferenc-** [comment]
The change has been merged, buildbot build has been published, the `app.organicmaps.desktop.Debug` is now installed,
and I still don't see any debug symbols. Do you?

````
(No debugging symbols found in /app/bin/OMaps)
````

**Pull request merged**
