### PR TITLE
Update version to 2023.01.25-3

### PR DESCRIPTION
**Pull request by Ferenc-**
Signed-off-by: Ferenc Géczi <ferenc.gm@gmail.com>

### CODE REVIEW

**Review by biodranik — COMMENTED** [review]
https://organicmaps.app/news/2023-01-27/we-are-excited-to-announce-our-first-update-of-2023/

iOS and Android can be removed.

**Comment by Ferenc-** [comment]
> https://organicmaps.app/news/2023-01-27/we-are-excited-to-announce-our-first-update-of-2023/
> 
> iOS and Android can be removed.

Done

**Review by biodranik — APPROVED** [review]

**Comment by Ferenc-** [comment]
@biodranik Thank you for the approval. The test build works on my side. Is there anything needed before merge?

**Comment by biodranik** [comment]
@Ferenc- don't you have rights to merge? Who can provide them to you?

**Comment by fgaz** [comment]
#22

**Pull request merged**
